
spring:
  application:
    name: hello-demo
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/,http://localhost:10001/eureka/,http://localhost:10002/eureka/


