server:
  port: 8080

spring:
  #mysql 配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.28.137:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  #redis 配置
  redis:
    #redis服务器地址
    host: 192.168.28.137
    #redis连接端口号
    port: 6379
    #redis连接密码
    password:
    #redis连接超时时间（毫秒）
    timeout: 2000

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
