server:
  port: 8080

spring:
  #mysql 配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.28.137:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  ##服务名字
  application:
    name: hello-demo

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

##配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/